### ISSUE TITLE
Poll 도메인에서 id 대신 code를 사용한다.

### ISSUE THREAD

**Issue by seong-wooo** [woowacourse-teams/2022-mo-rak#104]
## (필수) 구현할 기능에 명시한다.
Poll 도메인에서 id 대신 code를 사용한다.

## (필수) 구현하는데 필요한 작업을 설명한다.
- [x] poll 관련 PathVariable에 id 대신 code를 사용한다.
- [x] poll 관련 서비스에서 id 대신 code를 사용한다.

## (선택) 기능을 구현하며 주의해야할 사항을 명시한다.
1. code는 8글자로 고정한다.

**Comment by al-bur** [comment]
업데이트 완료되면 어떻게 바뀌는 지 공유 부탁드립니다!
