### ISSUE TITLE
약속잡기 생성할 때 이미 지난 시간을 선택해도 생성이 되는 버그

### ISSUE THREAD

**Issue by al-bur** [woowacourse-teams/2022-mo-rak#361]
## (필수) 버그에 대한 증상을 설명한다.
약속잡기 생성할 때 이미 지난 시간을 선택해도 생성이 됩니다.

## (선택) 버그를 설명할 수 있는 스크린샷을 첨부한다.
![image](https://user-images.githubusercontent.com/64825713/188057559-bb768f14-b19e-4da9-b9e3-43560f1382e7.png)

이미 지난 시간이어도 약속잡기가 생성이 되는 버그 사진
![image](https://user-images.githubusercontent.com/64825713/188057578-ba6e3fd1-51f0-4f5f-9c4a-291258eafaea.png)

**Comment by cjlee38** [comment]
9월2일 오후 1시에 생성했다고 쳤을 때, 시작시간을 '9월2일 오전 8시'로 설정한 경우에 생성이 가능한 경우를 말씀하신걸까요?

이 케이스가 맞다면, 버그가 아니라 의도된 경우입니다~ 누군가가 다른 날짜(e.g. 9월3일)도 포함하는 '시작시간 오전 8시' 약속을 생성하고 싶을 수도 있어서요.

**Comment by al-bur** [comment]
아 그렇군요!!! 의도된 것 확인했습니다~ 감사합니다
