### ISSUE TITLE
사이드바의 모달이 모여있는 컴포넌트 내부를 추상화한다. 

### ISSUE THREAD

**Issue by rladpwl0512** [woowacourse-teams/2022-mo-rak#390]
## (필수) 구현한 기능의 commit id 혹은 issue 번호를 명시한다.
#222 

## (필수) 리팩토링할 대상 혹은 작업 내용을 명시한다.
`SidebarMenuModals` 내부를 추상화한다.

**Comment by al-bur** [comment]
오래된 이슈라 close
