### ISSUE TITLE
접근성이 보장되어야 한다.

### ISSUE THREAD

**Issue by usageness** [woowacourse-teams/2022-mo-rak#436]
## (필수) 구현할 기능에 명시한다.
접근성을 위해 투표 기능에 tab-index와 선택시 알림 기능이 필요하다.

## (필수) 구현하는데 필요한 작업을 설명한다.

1. 각 투표 요소에 tab-index를 추가한다.
2. 선택하거나 취소하는 동작에 대해 알림 메시지를 읽어준다.

**Comment by rladpwl0512** [comment]
## (필수) 구현할 기능에 명시한다.
- 투표 기능에 대한 접근성을 보장한다. 
## (필수) 구현하는데 필요한 작업을 설명한다.
1. 대부분의 스크린리더기 사용자가 아이폰의 voiceover를 사용한다는 점을 고려하여, 투표하기 기능의 모바일 화면을 대응한다. 
2. 페이지별로 접근성을 대응한다. 
*각 투표 요소에 tab-index를 추가한다.
*선택하거나 취소하는 동작에 대해 알림 메시지를 읽어준다.
  
  - 투표 목록 페이지 
  - 투표 생성 페이지 
  - 투표 진행 페이지 
  - 투표 결과 페이지 

## refactor 
- [ ] 모바일일때와 아닐때로 나누어서 style 속성을 page 컴포넌트가 아닌, 외부에서 지정해줄까?  (고민)

**Comment by rladpwl0512** [comment]
- 그룹 생성 페이지에 접근성을 보장한다. (`GroupInitPage`)
