### ISSUE TITLE
`SimpleMockMvc`를 적용한다.

### ISSUE THREAD

**Issue by cjlee38** [woowacourse-teams/2022-mo-rak#493]
## (필수) 구현한 기능의 commit id 혹은 issue 번호를 명시한다.

#439 

[참고](https://github.com/woowacourse-teams/2022-mo-rak/pull/439#discussion_r1000204115)

## (필수) 리팩토링할 대상 혹은 작업 내용을 명시한다.
- SimpleMockMvc를 모든 컨트롤러 테스트에 적용한다.

**Comment by al-bur** [comment]
오래된 이슈라 종료합니다
