### ISSUE TITLE
도메인 재설계 이후 쿼리를 개선한다.

### ISSUE THREAD

**Issue by cjlee38** [woowacourse-teams/2022-mo-rak#494]
## (필수) 구현한 기능의 commit id 혹은 issue 번호를 명시한다.

#439 

## (필수) 리팩토링할 대상 혹은 작업 내용을 명시한다.
- 도메인 재설계 이후 쿼리를 개선한다.

**Comment by al-bur** [comment]
오래된 이슈라 종료합니다
