### ISSUE TITLE
추가된 컨벤션에 맞추어 코드를 수정한다.

### ISSUE THREAD

**Issue by rladpwl0512** [woowacourse-teams/2022-mo-rak#529]
## (필수) 리팩토링할 대상 혹은 작업 내용을 명시한다.
추가적으로 논의한 컨벤션에 맞추어 코드를 수정한다. 

- [x] 이미지 파일 import 네이밍 
- [x] lottie 파일 import 네이밍
- [x]  `-s`, `group` 네이밍 통일 
- [x]  logo -> service-logo

## 컨벤션 문서
[프론트엔드 코드 컨벤션🥳](https://www.notion.so/ririhan/Front-end-0c61b7388777431ebbff997885c9d1ea)

**Comment by al-bur** [comment]
StyledContainer 같은 컨벤션은 적용이 안된 것 같아 추가로 issue 생성해서 진행하겠습니다!

**Comment by al-bur** [comment]
https://github.com/woowacourse-teams/2022-mo-rak/issues/561
