### ISSUE TITLE
성능/로그 모니터링 서버 설정파일을 수정한다.

### ISSUE THREAD

**Issue by leo0842** [woowacourse-teams/2022-mo-rak#557]
## (필수) 구현할 기능에 명시한다.
무중단 배포시 떠있는 서버의 포트를 자동으로 갖추게 한다.

## (필수) 구현하는데 필요한 작업을 설명한다.
e.g. 
1. 설정 파일을 수정한다.

**Comment by al-bur** [comment]
오래된 이슈라 종료합니다
