### ISSUE TITLE
컨벤션에 따라 전반적인 리팩토링을 진행한다.

### ISSUE THREAD

**Issue by al-bur** [woowacourse-teams/2022-mo-rak#561]
## (필수) 리팩토링할 대상 혹은 작업 내용을 명시한다.
- 컨벤션에 따라 전반적인 리팩토링을 진행한다.

**Comment by rladpwl0512** [comment]
- [x] 최상위 styled component의 네이밍은 `StyledContainer` 이다.
- [x]  배경 색에 대한 값만 넣어주는 경우에는, `background` 대신 `background-color`를 사용한다. 
- [x]  top, bottom에 container 넣어주기
