### ISSUE TITLE
팀 도메인의 성능을 개선한다

### ISSUE THREAD

**Issue by seong-wooo** [woowacourse-teams/2022-mo-rak#572]
## (필수) 구현한 기능의 commit id 혹은 issue 번호를 명시한다.
none

## (필수) 리팩토링할 대상 혹은 작업 내용을 명시한다.
TeamCode로 TeamMember 조회 시 Cross Join이 걸리는 문제를 해결한다.

방법 1. 각 Service에서 teamRepository를 의존해서 team을 조회하고, 조회한 team으로 team에 속한 member들 조회하기
방법 2. foreign key를 team_id에서 team_code로 변경하기
방법 3. authorizationService.withTeamMemberValidation에서 사용할 수 있는 인터페이스를 더 만들기

<img width="478" alt="image" src="https://user-images.githubusercontent.com/79205414/200230935-b1b6dba5-d8d4-4c36-8317-2ff8de15c9c6.png">

**Comment by al-bur** [comment]
오래된 이슈라 종료합니다
