### ISSUE TITLE
그룹 메뉴 모달창을 닫는 기능을 구현한다. 

### ISSUE THREAD

**Issue by rladpwl0512** [woowacourse-teams/2022-mo-rak#578]
## (필수) 구현할 기능에 명시한다.
- 그룹 메뉴 모달창 이외의 공간을 클릭했을 때, 모달창이 닫히도록 만든다. 

## (필수) 구현하는데 필요한 작업을 설명한다.
- 그룹 메뉴 모달창 이외의 공간을 클릭했을 때, 모달창이 닫히도록 만든다. 

<img width="554" alt="스크린샷 2022-11-07 오후 5 29 51" src="https://user-images.githubusercontent.com/52344833/200262213-e58c0371-0c3e-40eb-8fd8-cc4293379eaa.png">

**Comment by al-bur** [comment]
오래된 이슈라 close
